version: "3.9"

services:
  web:
    build:
      context: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development   # "production" or "development"
    volumes:
      - nextjs_dev:/app
      - /app/node_modules

volumes:
  nextjs_dev:
